# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CTP\PyCTP\PyCTP_QT\QCTP\QCTP.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1622, 992)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tab_accounts = QtGui.QTabWidget(self.centralWidget)
        self.tab_accounts.setObjectName(_fromUtf8("tab_accounts"))
        self.tab_account1 = QtGui.QWidget()
        self.tab_account1.setObjectName(_fromUtf8("tab_account1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_account1)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.panel_show_account = QtGui.QWidget(self.tab_account1)
        self.panel_show_account.setObjectName(_fromUtf8("panel_show_account"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.panel_show_account)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_2 = QtGui.QWidget(self.panel_show_account)
        self.widget_2.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.label_19 = QtGui.QLabel(self.widget_2)
        self.label_19.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_30 = QtGui.QLabel(self.widget_2)
        self.label_30.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout.addWidget(self.widget_2)
        self.line_2 = QtGui.QFrame(self.panel_show_account)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.widget_3 = QtGui.QWidget(self.panel_show_account)
        self.widget_3.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.label_31 = QtGui.QLabel(self.widget_3)
        self.label_31.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.widget_3)
        self.label_32.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout.addWidget(self.widget_3)
        self.line_3 = QtGui.QFrame(self.panel_show_account)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.widget_4 = QtGui.QWidget(self.panel_show_account)
        self.widget_4.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.label_33 = QtGui.QLabel(self.widget_4)
        self.label_33.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.widget_4)
        self.label_34.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout.addWidget(self.widget_4)
        self.line_4 = QtGui.QFrame(self.panel_show_account)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.widget_5 = QtGui.QWidget(self.panel_show_account)
        self.widget_5.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.label_51 = QtGui.QLabel(self.widget_5)
        self.label_51.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.label_52 = QtGui.QLabel(self.widget_5)
        self.label_52.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout.addWidget(self.widget_5)
        self.line_5 = QtGui.QFrame(self.panel_show_account)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout.addWidget(self.line_5)
        self.widget_6 = QtGui.QWidget(self.panel_show_account)
        self.widget_6.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.label_53 = QtGui.QLabel(self.widget_6)
        self.label_53.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_54 = QtGui.QLabel(self.widget_6)
        self.label_54.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout.addWidget(self.widget_6)
        self.line_6 = QtGui.QFrame(self.panel_show_account)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout.addWidget(self.line_6)
        self.widget_7 = QtGui.QWidget(self.panel_show_account)
        self.widget_7.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_7.setObjectName(_fromUtf8("widget_7"))
        self.label_55 = QtGui.QLabel(self.widget_7)
        self.label_55.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_56 = QtGui.QLabel(self.widget_7)
        self.label_56.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.horizontalLayout.addWidget(self.widget_7)
        self.line_7 = QtGui.QFrame(self.panel_show_account)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout.addWidget(self.line_7)
        self.widget_8 = QtGui.QWidget(self.panel_show_account)
        self.widget_8.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_8.setObjectName(_fromUtf8("widget_8"))
        self.label_57 = QtGui.QLabel(self.widget_8)
        self.label_57.setGeometry(QtCore.QRect(16, 4, 75, 17))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_58 = QtGui.QLabel(self.widget_8)
        self.label_58.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.horizontalLayout.addWidget(self.widget_8)
        self.line_8 = QtGui.QFrame(self.panel_show_account)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout.addWidget(self.line_8)
        self.widget_9 = QtGui.QWidget(self.panel_show_account)
        self.widget_9.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_9.setObjectName(_fromUtf8("widget_9"))
        self.label_59 = QtGui.QLabel(self.widget_9)
        self.label_59.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_60 = QtGui.QLabel(self.widget_9)
        self.label_60.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.horizontalLayout.addWidget(self.widget_9)
        self.line_9 = QtGui.QFrame(self.panel_show_account)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.horizontalLayout.addWidget(self.line_9)
        self.widget_10 = QtGui.QWidget(self.panel_show_account)
        self.widget_10.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_10.setObjectName(_fromUtf8("widget_10"))
        self.label_61 = QtGui.QLabel(self.widget_10)
        self.label_61.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.label_62 = QtGui.QLabel(self.widget_10)
        self.label_62.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.horizontalLayout.addWidget(self.widget_10)
        self.line_10 = QtGui.QFrame(self.panel_show_account)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout.addWidget(self.line_10)
        self.widget_11 = QtGui.QWidget(self.panel_show_account)
        self.widget_11.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.label_63 = QtGui.QLabel(self.widget_11)
        self.label_63.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.widget_11)
        self.label_64.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.horizontalLayout.addWidget(self.widget_11)
        self.line_11 = QtGui.QFrame(self.panel_show_account)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout.addWidget(self.line_11)
        self.widget_12 = QtGui.QWidget(self.panel_show_account)
        self.widget_12.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_12.setObjectName(_fromUtf8("widget_12"))
        self.label_65 = QtGui.QLabel(self.widget_12)
        self.label_65.setGeometry(QtCore.QRect(16, 4, 67, 17))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.widget_12)
        self.label_66.setGeometry(QtCore.QRect(14, 16, 69, 27))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout.addWidget(self.widget_12)
        self.line_12 = QtGui.QFrame(self.panel_show_account)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.horizontalLayout.addWidget(self.line_12)
        self.pushButton_6 = QtGui.QPushButton(self.panel_show_account)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_8 = QtGui.QPushButton(self.panel_show_account)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_7 = QtGui.QPushButton(self.panel_show_account)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.verticalLayout_2.addWidget(self.panel_show_account)
        self.container_trade = QtGui.QWidget(self.tab_account1)
        self.container_trade.setObjectName(_fromUtf8("container_trade"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.container_trade)
        self.horizontalLayout_2.setMargin(5)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tablewidget_trade_args = QtGui.QTableWidget(self.container_trade)
        self.tablewidget_trade_args.setObjectName(_fromUtf8("tablewidget_trade_args"))
        self.tablewidget_trade_args.setColumnCount(15)
        self.tablewidget_trade_args.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(170, 168, 150))
        self.tablewidget_trade_args.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.tablewidget_trade_args.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.tablewidget_trade_args.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tablewidget_trade_args.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_trade_args.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tablewidget_trade_args.setItem(1, 0, item)
        self.horizontalLayout_2.addWidget(self.tablewidget_trade_args)
        self.groupBox_trade_args = QtGui.QGroupBox(self.container_trade)
        self.groupBox_trade_args.setObjectName(_fromUtf8("groupBox_trade_args"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_trade_args)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_trade_args)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_trade_args)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 3)
        self.label_2 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_trade_args)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_trade_args)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout.addWidget(self.spinBox_2, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout.addWidget(self.spinBox_3, 3, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 4, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 4, 2, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout.addWidget(self.spinBox_4, 4, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 5, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_trade_args)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 5, 2, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_trade_args)
        self.doubleSpinBox.setMaximum(99999.0)
        self.doubleSpinBox.setProperty("value", 12345.67)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout.addWidget(self.doubleSpinBox, 6, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 6, 2, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 6, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 7, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.groupBox_trade_args)
        self.doubleSpinBox_2.setMaximum(99999.0)
        self.doubleSpinBox_2.setProperty("value", 12345.67)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout.addWidget(self.doubleSpinBox_2, 7, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 7, 2, 1, 1)
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.gridLayout.addWidget(self.lineEdit_5, 7, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 8, 0, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.groupBox_trade_args)
        self.doubleSpinBox_3.setMaximum(99999.0)
        self.doubleSpinBox_3.setProperty("value", 12345.67)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout.addWidget(self.doubleSpinBox_3, 8, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 8, 2, 1, 1)
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout.addWidget(self.lineEdit_6, 8, 3, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 9, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.groupBox_trade_args)
        self.doubleSpinBox_4.setMaximum(99999.0)
        self.doubleSpinBox_4.setProperty("value", 12345.67)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout.addWidget(self.doubleSpinBox_4, 9, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 9, 2, 1, 1)
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.gridLayout.addWidget(self.lineEdit_7, 9, 3, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox_trade_args)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 10, 0, 1, 2)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_trade_args)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 10, 2, 1, 2)
        self.horizontalLayout_2.addWidget(self.groupBox_trade_args)
        self.horizontalLayout_2.setStretch(0, 6)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.addWidget(self.container_trade)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.tab_accounts.addTab(self.tab_account1, _fromUtf8(""))
        self.tab_account2 = QtGui.QWidget()
        self.tab_account2.setObjectName(_fromUtf8("tab_account2"))
        self.tab_accounts.addTab(self.tab_account2, _fromUtf8(""))
        self.tab_account3 = QtGui.QWidget()
        self.tab_account3.setObjectName(_fromUtf8("tab_account3"))
        self.tab_accounts.addTab(self.tab_account3, _fromUtf8(""))
        self.tab_account4 = QtGui.QWidget()
        self.tab_account4.setObjectName(_fromUtf8("tab_account4"))
        self.tab_accounts.addTab(self.tab_account4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_accounts)
        self.tab_records = QtGui.QTabWidget(self.centralWidget)
        self.tab_records.setObjectName(_fromUtf8("tab_records"))
        self.tab_order = QtGui.QWidget()
        self.tab_order.setObjectName(_fromUtf8("tab_order"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_order)
        self.horizontalLayout_4.setMargin(5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.container_order = QtGui.QWidget(self.tab_order)
        self.container_order.setObjectName(_fromUtf8("container_order"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.container_order)
        self.horizontalLayout_3.setMargin(5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableWidget_2 = QtGui.QTableWidget(self.container_order)
        self.tableWidget_2.setObjectName(_fromUtf8("tableWidget_2"))
        self.tableWidget_2.setColumnCount(16)
        self.tableWidget_2.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 14, item)
        self.horizontalLayout_3.addWidget(self.tableWidget_2)
        self.groupBox_2 = QtGui.QGroupBox(self.container_order)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 2, 1)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.gridLayout_2.addWidget(self.lineEdit_8, 0, 1, 2, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_2.addWidget(self.checkBox_2, 0, 2, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_2.addWidget(self.checkBox_3, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_2.addWidget(self.radioButton, 2, 1, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_2.addWidget(self.radioButton_2, 2, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 3, 0, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_2.addWidget(self.radioButton_3, 3, 1, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_2.addWidget(self.radioButton_4, 3, 2, 1, 1)
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.gridLayout_2.addWidget(self.radioButton_5, 3, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_2.addWidget(self.label_23, 4, 0, 2, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_2.addWidget(self.spinBox_5, 4, 1, 2, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 4, 2, 1, 2)
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 5, 2, 1, 2)
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 6, 0, 2, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_5.setMaximum(99999.0)
        self.doubleSpinBox_5.setProperty("value", 12345.67)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_5, 6, 1, 2, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 6, 2, 1, 2)
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 7, 2, 1, 2)
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 8, 2, 1, 2)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 9, 0, 2, 2)
        self.pushButton_4 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 9, 2, 1, 2)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 10, 2, 1, 2)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_3.setStretch(0, 6)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_4.addWidget(self.container_order)
        self.tab_records.addTab(self.tab_order, _fromUtf8(""))
        self.tab_unmatched = QtGui.QWidget()
        self.tab_unmatched.setObjectName(_fromUtf8("tab_unmatched"))
        self.tab_records.addTab(self.tab_unmatched, _fromUtf8(""))
        self.tab_transaction = QtGui.QWidget()
        self.tab_transaction.setObjectName(_fromUtf8("tab_transaction"))
        self.tab_records.addTab(self.tab_transaction, _fromUtf8(""))
        self.tab_position = QtGui.QWidget()
        self.tab_position.setObjectName(_fromUtf8("tab_position"))
        self.tab_records.addTab(self.tab_position, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_records)
        self.verticalLayout.setStretch(0, 4)
        self.verticalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1622, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_file = QtGui.QMenu(self.menuBar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_account = QtGui.QMenu(self.menuBar)
        self.menu_account.setObjectName(_fromUtf8("menu_account"))
        self.menu_market = QtGui.QMenu(self.menuBar)
        self.menu_market.setObjectName(_fromUtf8("menu_market"))
        self.menu_trademodel = QtGui.QMenu(self.menuBar)
        self.menu_trademodel.setObjectName(_fromUtf8("menu_trademodel"))
        self.menu_report = QtGui.QMenu(self.menuBar)
        self.menu_report.setObjectName(_fromUtf8("menu_report"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_account.menuAction())
        self.menuBar.addAction(self.menu_market.menuAction())
        self.menuBar.addAction(self.menu_trademodel.menuAction())
        self.menuBar.addAction(self.menu_report.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_accounts.setCurrentIndex(0)
        self.tab_records.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QCTP", None))
        self.label_19.setText(_translate("MainWindow", "动态权益", None))
        self.label_30.setText(_translate("MainWindow", "10000000", None))
        self.label_31.setText(_translate("MainWindow", "静态权益", None))
        self.label_32.setText(_translate("MainWindow", "10000000", None))
        self.label_33.setText(_translate("MainWindow", "持仓盈亏", None))
        self.label_34.setText(_translate("MainWindow", "10000000", None))
        self.label_51.setText(_translate("MainWindow", "平仓盈亏", None))
        self.label_52.setText(_translate("MainWindow", "10000000", None))
        self.label_53.setText(_translate("MainWindow", "手续费", None))
        self.label_54.setText(_translate("MainWindow", "10000000", None))
        self.label_55.setText(_translate("MainWindow", "可用资金", None))
        self.label_56.setText(_translate("MainWindow", "10000000", None))
        self.label_57.setText(_translate("MainWindow", "占用保证金", None))
        self.label_58.setText(_translate("MainWindow", "10000000", None))
        self.label_59.setText(_translate("MainWindow", "下单冻结", None))
        self.label_60.setText(_translate("MainWindow", "10000000", None))
        self.label_61.setText(_translate("MainWindow", "风险度", None))
        self.label_62.setText(_translate("MainWindow", "10000000", None))
        self.label_63.setText(_translate("MainWindow", "今日入金", None))
        self.label_64.setText(_translate("MainWindow", "10000000", None))
        self.label_65.setText(_translate("MainWindow", "今日出金", None))
        self.label_66.setText(_translate("MainWindow", "10000000", None))
        self.pushButton_6.setText(_translate("MainWindow", "查询账户", None))
        self.pushButton_8.setText(_translate("MainWindow", "只能平仓", None))
        self.pushButton_7.setText(_translate("MainWindow", "开始策略", None))
        item = self.tablewidget_trade_args.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tablewidget_trade_args.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "策略开关", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "期货账号", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "策略编号", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "交易合约", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "新建列", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "交易模型参数", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "持仓盈亏", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "手续费", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "总持仓", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "买持仓", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "新建列", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "卖持仓", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "成交量", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "成交金额", None))
        item = self.tablewidget_trade_args.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "平均滑点", None))
        __sortingEnabled = self.tablewidget_trade_args.isSortingEnabled()
        self.tablewidget_trade_args.setSortingEnabled(False)
        item = self.tablewidget_trade_args.item(0, 0)
        item.setText(_translate("MainWindow", "开", None))
        item = self.tablewidget_trade_args.item(0, 1)
        item.setText(_translate("MainWindow", "800xxxx", None))
        item = self.tablewidget_trade_args.item(1, 0)
        item.setText(_translate("MainWindow", "关", None))
        self.tablewidget_trade_args.setSortingEnabled(__sortingEnabled)
        self.groupBox_trade_args.setTitle(_translate("MainWindow", "策略参数", None))
        self.label.setText(_translate("MainWindow", "期货账号", None))
        self.label_2.setText(_translate("MainWindow", "策略编号", None))
        self.label_3.setText(_translate("MainWindow", "下单算法", None))
        self.label_4.setText(_translate("MainWindow", "交易模型", None))
        self.label_5.setText(_translate("MainWindow", "止损跳数", None))
        self.label_6.setText(_translate("MainWindow", "空头价差", None))
        self.label_7.setText(_translate("MainWindow", "总手", None))
        self.label_9.setText(_translate("MainWindow", "多头价差", None))
        self.label_8.setText(_translate("MainWindow", "每份", None))
        self.label_10.setText(_translate("MainWindow", "价差让价", None))
        self.checkBox.setText(_translate("MainWindow", "价差联动", None))
        self.label_11.setText(_translate("MainWindow", "空头开", None))
        self.label_12.setText(_translate("MainWindow", "A卖持仓", None))
        self.lineEdit_4.setText(_translate("MainWindow", "10", None))
        self.label_14.setText(_translate("MainWindow", "空头平", None))
        self.label_13.setText(_translate("MainWindow", "B买持仓", None))
        self.lineEdit_5.setText(_translate("MainWindow", "10", None))
        self.label_16.setText(_translate("MainWindow", "多头平", None))
        self.label_15.setText(_translate("MainWindow", "A买持仓", None))
        self.lineEdit_6.setText(_translate("MainWindow", "10", None))
        self.label_18.setText(_translate("MainWindow", "多头开", None))
        self.label_17.setText(_translate("MainWindow", "B卖持仓", None))
        self.lineEdit_7.setText(_translate("MainWindow", "10", None))
        self.pushButton.setText(_translate("MainWindow", "确定", None))
        self.pushButton_2.setText(_translate("MainWindow", "查询", None))
        self.tab_accounts.setTabText(self.tab_accounts.indexOf(self.tab_account1), _translate("MainWindow", "所有账户", None))
        self.tab_accounts.setTabText(self.tab_accounts.indexOf(self.tab_account2), _translate("MainWindow", "800658", None))
        self.tab_accounts.setTabText(self.tab_accounts.indexOf(self.tab_account3), _translate("MainWindow", "800669", None))
        self.tab_accounts.setTabText(self.tab_accounts.indexOf(self.tab_account4), _translate("MainWindow", "86001780", None))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "期货账号", None))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "策略编号", None))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "合约", None))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "买卖", None))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "开平", None))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "挂单状态", None))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "报单价格", None))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "报单手数", None))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "未成交手数", None))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "成交手数", None))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "详细状态", None))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "报单时间", None))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "最后成交时间", None))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "报单编号", None))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "投保", None))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "交易所", None))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "800658", None))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "cu1610", None))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "买", None))
        item = self.tableWidget_2.item(0, 4)
        item.setText(_translate("MainWindow", "开", None))
        item = self.tableWidget_2.item(0, 5)
        item.setText(_translate("MainWindow", "未成交", None))
        item = self.tableWidget_2.item(0, 6)
        item.setText(_translate("MainWindow", "82990", None))
        item = self.tableWidget_2.item(0, 7)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_2.item(0, 8)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_2.item(0, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_2.item(0, 10)
        item.setText(_translate("MainWindow", "未成交", None))
        item = self.tableWidget_2.item(0, 13)
        item.setText(_translate("MainWindow", "291759", None))
        item = self.tableWidget_2.item(0, 14)
        item.setText(_translate("MainWindow", "投机", None))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.groupBox_2.setTitle(_translate("MainWindow", "下单板", None))
        self.label_20.setText(_translate("MainWindow", "合约", None))
        self.lineEdit_8.setText(_translate("MainWindow", "cu1610", None))
        self.checkBox_2.setText(_translate("MainWindow", "套利", None))
        self.checkBox_3.setText(_translate("MainWindow", "保值", None))
        self.label_21.setText(_translate("MainWindow", "买卖", None))
        self.radioButton.setText(_translate("MainWindow", "买入", None))
        self.radioButton_2.setText(_translate("MainWindow", "卖出", None))
        self.label_22.setText(_translate("MainWindow", "开平", None))
        self.radioButton_3.setText(_translate("MainWindow", "开仓", None))
        self.radioButton_4.setText(_translate("MainWindow", "平仓", None))
        self.radioButton_5.setText(_translate("MainWindow", "平今", None))
        self.label_23.setText(_translate("MainWindow", "手数", None))
        self.label_24.setText(_translate("MainWindow", "≤0", None))
        self.label_25.setText(_translate("MainWindow", "↑88020", None))
        self.label_26.setText(_translate("MainWindow", "价格", None))
        self.label_27.setText(_translate("MainWindow", "卖 82990 / 3", None))
        self.label_28.setText(_translate("MainWindow", "买 82970 / 20", None))
        self.label_29.setText(_translate("MainWindow", "↓88020", None))
        self.pushButton_3.setText(_translate("MainWindow", "下单", None))
        self.pushButton_4.setText(_translate("MainWindow", "取消", None))
        self.pushButton_5.setText(_translate("MainWindow", "调仓", None))
        self.tab_records.setTabText(self.tab_records.indexOf(self.tab_order), _translate("MainWindow", "所有委托单", None))
        self.tab_records.setTabText(self.tab_records.indexOf(self.tab_unmatched), _translate("MainWindow", "未成交单", None))
        self.tab_records.setTabText(self.tab_records.indexOf(self.tab_transaction), _translate("MainWindow", "成交记录", None))
        self.tab_records.setTabText(self.tab_records.indexOf(self.tab_position), _translate("MainWindow", "持仓", None))
        self.menu_file.setTitle(_translate("MainWindow", "文件", None))
        self.menu_account.setTitle(_translate("MainWindow", "账户", None))
        self.menu_market.setTitle(_translate("MainWindow", "行情", None))
        self.menu_trademodel.setTitle(_translate("MainWindow", "交易模型", None))
        self.menu_report.setTitle(_translate("MainWindow", "报告", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

