# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\CTP\PyCTP\PyCTP_QT\QCTP\QCTP.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1276, 900)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tab_accounts = QtGui.QTabWidget(self.centralWidget)
        self.tab_accounts.setObjectName(_fromUtf8("tab_accounts"))
        self.tab_account1 = QtGui.QWidget()
        self.tab_account1.setObjectName(_fromUtf8("tab_account1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_account1)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.panel_show_account = QtGui.QWidget(self.tab_account1)
        self.panel_show_account.setObjectName(_fromUtf8("panel_show_account"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.panel_show_account)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.widget_dongtaiquanyi = QtGui.QWidget(self.panel_show_account)
        self.widget_dongtaiquanyi.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_dongtaiquanyi.setObjectName(_fromUtf8("widget_dongtaiquanyi"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget_dongtaiquanyi)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_dongtaiquanyi = QtGui.QLabel(self.widget_dongtaiquanyi)
        self.label_dongtaiquanyi.setObjectName(_fromUtf8("label_dongtaiquanyi"))
        self.gridLayout_5.addWidget(self.label_dongtaiquanyi, 0, 0, 1, 1)
        self.label_value_dongtaiquanyi = QtGui.QLabel(self.widget_dongtaiquanyi)
        self.label_value_dongtaiquanyi.setObjectName(_fromUtf8("label_value_dongtaiquanyi"))
        self.gridLayout_5.addWidget(self.label_value_dongtaiquanyi, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.widget_dongtaiquanyi)
        self.line_13 = QtGui.QFrame(self.panel_show_account)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.horizontalLayout_2.addWidget(self.line_13)
        self.widget_jingtaiquanyi = QtGui.QWidget(self.panel_show_account)
        self.widget_jingtaiquanyi.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_jingtaiquanyi.setObjectName(_fromUtf8("widget_jingtaiquanyi"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_jingtaiquanyi)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_jingtaiquanyi = QtGui.QLabel(self.widget_jingtaiquanyi)
        self.label_jingtaiquanyi.setObjectName(_fromUtf8("label_jingtaiquanyi"))
        self.verticalLayout_3.addWidget(self.label_jingtaiquanyi)
        self.label_value_jingtaiquanyi = QtGui.QLabel(self.widget_jingtaiquanyi)
        self.label_value_jingtaiquanyi.setObjectName(_fromUtf8("label_value_jingtaiquanyi"))
        self.verticalLayout_3.addWidget(self.label_value_jingtaiquanyi)
        self.horizontalLayout_2.addWidget(self.widget_jingtaiquanyi)
        self.line_14 = QtGui.QFrame(self.panel_show_account)
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.horizontalLayout_2.addWidget(self.line_14)
        self.widget_chicangyingkui = QtGui.QWidget(self.panel_show_account)
        self.widget_chicangyingkui.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_chicangyingkui.setObjectName(_fromUtf8("widget_chicangyingkui"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_chicangyingkui)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_chicangyingkui = QtGui.QLabel(self.widget_chicangyingkui)
        self.label_chicangyingkui.setObjectName(_fromUtf8("label_chicangyingkui"))
        self.verticalLayout_8.addWidget(self.label_chicangyingkui)
        self.label_value_chicangyingkui = QtGui.QLabel(self.widget_chicangyingkui)
        self.label_value_chicangyingkui.setObjectName(_fromUtf8("label_value_chicangyingkui"))
        self.verticalLayout_8.addWidget(self.label_value_chicangyingkui)
        self.horizontalLayout_2.addWidget(self.widget_chicangyingkui)
        self.line_15 = QtGui.QFrame(self.panel_show_account)
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.horizontalLayout_2.addWidget(self.line_15)
        self.widget_pingcangyingkui = QtGui.QWidget(self.panel_show_account)
        self.widget_pingcangyingkui.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_pingcangyingkui.setObjectName(_fromUtf8("widget_pingcangyingkui"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_pingcangyingkui)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_pingcangyingkui = QtGui.QLabel(self.widget_pingcangyingkui)
        self.label_pingcangyingkui.setObjectName(_fromUtf8("label_pingcangyingkui"))
        self.verticalLayout_9.addWidget(self.label_pingcangyingkui)
        self.label_value_pingcangyingkui = QtGui.QLabel(self.widget_pingcangyingkui)
        self.label_value_pingcangyingkui.setObjectName(_fromUtf8("label_value_pingcangyingkui"))
        self.verticalLayout_9.addWidget(self.label_value_pingcangyingkui)
        self.horizontalLayout_2.addWidget(self.widget_pingcangyingkui)
        self.line_16 = QtGui.QFrame(self.panel_show_account)
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.horizontalLayout_2.addWidget(self.line_16)
        self.widget_shouxufei = QtGui.QWidget(self.panel_show_account)
        self.widget_shouxufei.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_shouxufei.setObjectName(_fromUtf8("widget_shouxufei"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget_shouxufei)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_shouxufei = QtGui.QLabel(self.widget_shouxufei)
        self.label_shouxufei.setObjectName(_fromUtf8("label_shouxufei"))
        self.verticalLayout_10.addWidget(self.label_shouxufei)
        self.label_value_shouxufei = QtGui.QLabel(self.widget_shouxufei)
        self.label_value_shouxufei.setObjectName(_fromUtf8("label_value_shouxufei"))
        self.verticalLayout_10.addWidget(self.label_value_shouxufei)
        self.horizontalLayout_2.addWidget(self.widget_shouxufei)
        self.line_17 = QtGui.QFrame(self.panel_show_account)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.horizontalLayout_2.addWidget(self.line_17)
        self.widget_keyongzijin = QtGui.QWidget(self.panel_show_account)
        self.widget_keyongzijin.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_keyongzijin.setObjectName(_fromUtf8("widget_keyongzijin"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widget_keyongzijin)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_keyongzijin = QtGui.QLabel(self.widget_keyongzijin)
        self.label_keyongzijin.setObjectName(_fromUtf8("label_keyongzijin"))
        self.verticalLayout_11.addWidget(self.label_keyongzijin)
        self.label_value_keyongzijin = QtGui.QLabel(self.widget_keyongzijin)
        self.label_value_keyongzijin.setObjectName(_fromUtf8("label_value_keyongzijin"))
        self.verticalLayout_11.addWidget(self.label_value_keyongzijin)
        self.horizontalLayout_2.addWidget(self.widget_keyongzijin)
        self.line_18 = QtGui.QFrame(self.panel_show_account)
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.horizontalLayout_2.addWidget(self.line_18)
        self.widget_zhanyongbaozhengjin = QtGui.QWidget(self.panel_show_account)
        self.widget_zhanyongbaozhengjin.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_zhanyongbaozhengjin.setObjectName(_fromUtf8("widget_zhanyongbaozhengjin"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.widget_zhanyongbaozhengjin)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_zhanyongbaozhengjin = QtGui.QLabel(self.widget_zhanyongbaozhengjin)
        self.label_zhanyongbaozhengjin.setObjectName(_fromUtf8("label_zhanyongbaozhengjin"))
        self.verticalLayout_12.addWidget(self.label_zhanyongbaozhengjin)
        self.label_value_zhanyongbaozhengjin = QtGui.QLabel(self.widget_zhanyongbaozhengjin)
        self.label_value_zhanyongbaozhengjin.setObjectName(_fromUtf8("label_value_zhanyongbaozhengjin"))
        self.verticalLayout_12.addWidget(self.label_value_zhanyongbaozhengjin)
        self.horizontalLayout_2.addWidget(self.widget_zhanyongbaozhengjin)
        self.line_19 = QtGui.QFrame(self.panel_show_account)
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.horizontalLayout_2.addWidget(self.line_19)
        self.widget_xiadandongjie = QtGui.QWidget(self.panel_show_account)
        self.widget_xiadandongjie.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_xiadandongjie.setObjectName(_fromUtf8("widget_xiadandongjie"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.widget_xiadandongjie)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_xiadandongjie = QtGui.QLabel(self.widget_xiadandongjie)
        self.label_xiadandongjie.setObjectName(_fromUtf8("label_xiadandongjie"))
        self.verticalLayout_13.addWidget(self.label_xiadandongjie)
        self.label_value_xiadandongjie = QtGui.QLabel(self.widget_xiadandongjie)
        self.label_value_xiadandongjie.setObjectName(_fromUtf8("label_value_xiadandongjie"))
        self.verticalLayout_13.addWidget(self.label_value_xiadandongjie)
        self.horizontalLayout_2.addWidget(self.widget_xiadandongjie)
        self.line_20 = QtGui.QFrame(self.panel_show_account)
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.horizontalLayout_2.addWidget(self.line_20)
        self.widget_fengxiandu = QtGui.QWidget(self.panel_show_account)
        self.widget_fengxiandu.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_fengxiandu.setObjectName(_fromUtf8("widget_fengxiandu"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_fengxiandu)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_fengxiandu = QtGui.QLabel(self.widget_fengxiandu)
        self.label_fengxiandu.setObjectName(_fromUtf8("label_fengxiandu"))
        self.verticalLayout_5.addWidget(self.label_fengxiandu)
        self.label_value_fengxiandu = QtGui.QLabel(self.widget_fengxiandu)
        self.label_value_fengxiandu.setObjectName(_fromUtf8("label_value_fengxiandu"))
        self.verticalLayout_5.addWidget(self.label_value_fengxiandu)
        self.horizontalLayout_2.addWidget(self.widget_fengxiandu)
        self.line_10 = QtGui.QFrame(self.panel_show_account)
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.horizontalLayout_2.addWidget(self.line_10)
        self.widget_jinrirujin = QtGui.QWidget(self.panel_show_account)
        self.widget_jinrirujin.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_jinrirujin.setObjectName(_fromUtf8("widget_jinrirujin"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_jinrirujin)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_jinrirujin = QtGui.QLabel(self.widget_jinrirujin)
        self.label_jinrirujin.setObjectName(_fromUtf8("label_jinrirujin"))
        self.verticalLayout_6.addWidget(self.label_jinrirujin)
        self.label_value_jinrirujin = QtGui.QLabel(self.widget_jinrirujin)
        self.label_value_jinrirujin.setObjectName(_fromUtf8("label_value_jinrirujin"))
        self.verticalLayout_6.addWidget(self.label_value_jinrirujin)
        self.horizontalLayout_2.addWidget(self.widget_jinrirujin)
        self.line_11 = QtGui.QFrame(self.panel_show_account)
        self.line_11.setFrameShape(QtGui.QFrame.VLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.horizontalLayout_2.addWidget(self.line_11)
        self.widget_jinrichujin = QtGui.QWidget(self.panel_show_account)
        self.widget_jinrichujin.setStyleSheet(_fromUtf8("border-right-color: rgb(170, 164, 162);"))
        self.widget_jinrichujin.setObjectName(_fromUtf8("widget_jinrichujin"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_jinrichujin)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_jinrichujin = QtGui.QLabel(self.widget_jinrichujin)
        self.label_jinrichujin.setObjectName(_fromUtf8("label_jinrichujin"))
        self.verticalLayout_7.addWidget(self.label_jinrichujin)
        self.label_value_jinrichujin = QtGui.QLabel(self.widget_jinrichujin)
        self.label_value_jinrichujin.setObjectName(_fromUtf8("label_value_jinrichujin"))
        self.verticalLayout_7.addWidget(self.label_value_jinrichujin)
        self.horizontalLayout_2.addWidget(self.widget_jinrichujin)
        self.line_12 = QtGui.QFrame(self.panel_show_account)
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.horizontalLayout_2.addWidget(self.line_12)
        self.pushButton_query_account = QtGui.QPushButton(self.panel_show_account)
        self.pushButton_query_account.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_query_account.setObjectName(_fromUtf8("pushButton_query_account"))
        self.horizontalLayout_2.addWidget(self.pushButton_query_account)
        self.pushButton_only_close = QtGui.QPushButton(self.panel_show_account)
        self.pushButton_only_close.setObjectName(_fromUtf8("pushButton_only_close"))
        self.horizontalLayout_2.addWidget(self.pushButton_only_close)
        self.pushButton_start_strategy = QtGui.QPushButton(self.panel_show_account)
        self.pushButton_start_strategy.setObjectName(_fromUtf8("pushButton_start_strategy"))
        self.horizontalLayout_2.addWidget(self.pushButton_start_strategy)
        self.verticalLayout.addWidget(self.panel_show_account)
        self.container_trade = QtGui.QWidget(self.tab_account1)
        self.container_trade.setObjectName(_fromUtf8("container_trade"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.container_trade)
        self.horizontalLayout.setMargin(5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tablewidget_tableWidget_Trade_Args = QtGui.QTableWidget(self.container_trade)
        self.tablewidget_tableWidget_Trade_Args.setEnabled(True)
        self.tablewidget_tableWidget_Trade_Args.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tablewidget_tableWidget_Trade_Args.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tablewidget_tableWidget_Trade_Args.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tablewidget_tableWidget_Trade_Args.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tablewidget_tableWidget_Trade_Args.setShowGrid(True)
        self.tablewidget_tableWidget_Trade_Args.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.tablewidget_tableWidget_Trade_Args.setObjectName(_fromUtf8("tablewidget_tableWidget_Trade_Args"))
        self.tablewidget_tableWidget_Trade_Args.setColumnCount(15)
        self.tablewidget_tableWidget_Trade_Args.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setBackground(QtGui.QColor(170, 168, 150))
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tablewidget_tableWidget_Trade_Args.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tablewidget_tableWidget_Trade_Args.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.tablewidget_tableWidget_Trade_Args.setItem(1, 0, item)
        self.tablewidget_tableWidget_Trade_Args.horizontalHeader().setVisible(True)
        self.tablewidget_tableWidget_Trade_Args.horizontalHeader().setSortIndicatorShown(False)
        self.tablewidget_tableWidget_Trade_Args.horizontalHeader().setStretchLastSection(False)
        self.tablewidget_tableWidget_Trade_Args.verticalHeader().setVisible(False)
        self.tablewidget_tableWidget_Trade_Args.verticalHeader().setCascadingSectionResizes(False)
        self.tablewidget_tableWidget_Trade_Args.verticalHeader().setHighlightSections(True)
        self.horizontalLayout.addWidget(self.tablewidget_tableWidget_Trade_Args)
        self.groupBox_trade_args = QtGui.QGroupBox(self.container_trade)
        self.groupBox_trade_args.setFlat(False)
        self.groupBox_trade_args.setCheckable(False)
        self.groupBox_trade_args.setObjectName(_fromUtf8("groupBox_trade_args"))
        self.label_kongtoujiacha = QtGui.QLabel(self.groupBox_trade_args)
        self.label_kongtoujiacha.setGeometry(QtCore.QRect(6, 120, 60, 16))
        self.label_kongtoujiacha.setObjectName(_fromUtf8("label_kongtoujiacha"))
        self.label_qihuozhanghao = QtGui.QLabel(self.groupBox_trade_args)
        self.label_qihuozhanghao.setGeometry(QtCore.QRect(6, 30, 60, 16))
        self.label_qihuozhanghao.setObjectName(_fromUtf8("label_qihuozhanghao"))
        self.label_jiaoyimoxing = QtGui.QLabel(self.groupBox_trade_args)
        self.label_jiaoyimoxing.setGeometry(QtCore.QRect(6, 60, 60, 16))
        self.label_jiaoyimoxing.setObjectName(_fromUtf8("label_jiaoyimoxing"))
        self.label_jiacharangjia = QtGui.QLabel(self.groupBox_trade_args)
        self.label_jiacharangjia.setGeometry(QtCore.QRect(120, 90, 35, 16))
        self.label_jiacharangjia.setObjectName(_fromUtf8("label_jiacharangjia"))
        self.label_duotoujiacha = QtGui.QLabel(self.groupBox_trade_args)
        self.label_duotoujiacha.setGeometry(QtCore.QRect(6, 150, 60, 16))
        self.label_duotoujiacha.setObjectName(_fromUtf8("label_duotoujiacha"))
        self.checkBox_jiachaliandong_2 = QtGui.QCheckBox(self.groupBox_trade_args)
        self.checkBox_jiachaliandong_2.setGeometry(QtCore.QRect(6, 180, 72, 19))
        self.checkBox_jiachaliandong_2.setObjectName(_fromUtf8("checkBox_jiachaliandong_2"))
        self.checkBox_jiachaliandong_4 = QtGui.QCheckBox(self.groupBox_trade_args)
        self.checkBox_jiachaliandong_4.setGeometry(QtCore.QRect(6, 240, 72, 19))
        self.checkBox_jiachaliandong_4.setObjectName(_fromUtf8("checkBox_jiachaliandong_4"))
        self.checkBox_jiachaliandong_3 = QtGui.QCheckBox(self.groupBox_trade_args)
        self.checkBox_jiachaliandong_3.setGeometry(QtCore.QRect(6, 270, 72, 19))
        self.checkBox_jiachaliandong_3.setObjectName(_fromUtf8("checkBox_jiachaliandong_3"))
        self.label_zongshou = QtGui.QLabel(self.groupBox_trade_args)
        self.label_zongshou.setGeometry(QtCore.QRect(300, 30, 30, 16))
        self.label_zongshou.setObjectName(_fromUtf8("label_zongshou"))
        self.comboBox_qihuozhanghao = QtGui.QComboBox(self.groupBox_trade_args)
        self.comboBox_qihuozhanghao.setGeometry(QtCore.QRect(78, 30, 105, 21))
        self.comboBox_qihuozhanghao.setObjectName(_fromUtf8("comboBox_qihuozhanghao"))
        self.comboBox_qihuozhanghao.addItem(_fromUtf8(""))
        self.comboBox_jiaoyimoxing = QtGui.QComboBox(self.groupBox_trade_args)
        self.comboBox_jiaoyimoxing.setGeometry(QtCore.QRect(78, 60, 105, 21))
        self.comboBox_jiaoyimoxing.setObjectName(_fromUtf8("comboBox_jiaoyimoxing"))
        self.checkBox_jiachaliandong_5 = QtGui.QCheckBox(self.groupBox_trade_args)
        self.checkBox_jiachaliandong_5.setGeometry(QtCore.QRect(6, 210, 72, 19))
        self.checkBox_jiachaliandong_5.setObjectName(_fromUtf8("checkBox_jiachaliandong_5"))
        self.spinBox_meifen = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_meifen.setGeometry(QtCore.QRect(334, 60, 55, 21))
        self.spinBox_meifen.setMaximum(9999)
        self.spinBox_meifen.setProperty("value", 9999)
        self.spinBox_meifen.setObjectName(_fromUtf8("spinBox_meifen"))
        self.label_celuebianhao = QtGui.QLabel(self.groupBox_trade_args)
        self.label_celuebianhao.setGeometry(QtCore.QRect(186, 30, 60, 16))
        self.label_celuebianhao.setObjectName(_fromUtf8("label_celuebianhao"))
        self.comboBox_celuebianhao = QtGui.QComboBox(self.groupBox_trade_args)
        self.comboBox_celuebianhao.setGeometry(QtCore.QRect(252, 30, 40, 21))
        self.comboBox_celuebianhao.setObjectName(_fromUtf8("comboBox_celuebianhao"))
        self.comboBox_celuebianhao.addItem(_fromUtf8(""))
        self.label_xiadansuanfa = QtGui.QLabel(self.groupBox_trade_args)
        self.label_xiadansuanfa.setGeometry(QtCore.QRect(186, 60, 60, 16))
        self.label_xiadansuanfa.setObjectName(_fromUtf8("label_xiadansuanfa"))
        self.spinBox_xiadansuanfa = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_xiadansuanfa.setGeometry(QtCore.QRect(252, 60, 40, 21))
        self.spinBox_xiadansuanfa.setObjectName(_fromUtf8("spinBox_xiadansuanfa"))
        self.label_meifen = QtGui.QLabel(self.groupBox_trade_args)
        self.label_meifen.setGeometry(QtCore.QRect(300, 60, 30, 16))
        self.label_meifen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_meifen.setObjectName(_fromUtf8("label_meifen"))
        self.spinBox_meifen_5 = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_meifen_5.setGeometry(QtCore.QRect(334, 30, 55, 21))
        self.spinBox_meifen_5.setMaximum(9999)
        self.spinBox_meifen_5.setProperty("value", 9999)
        self.spinBox_meifen_5.setObjectName(_fromUtf8("spinBox_meifen_5"))
        self.spinBox_meifen_2 = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_meifen_2.setGeometry(QtCore.QRect(156, 90, 42, 21))
        self.spinBox_meifen_2.setObjectName(_fromUtf8("spinBox_meifen_2"))
        self.lineEdit_kongtoujiacha = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_kongtoujiacha.setGeometry(QtCore.QRect(78, 120, 120, 21))
        self.lineEdit_kongtoujiacha.setObjectName(_fromUtf8("lineEdit_kongtoujiacha"))
        self.lineEdit_duotoujiacha = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_duotoujiacha.setGeometry(QtCore.QRect(78, 150, 120, 21))
        self.lineEdit_duotoujiacha.setObjectName(_fromUtf8("lineEdit_duotoujiacha"))
        self.doubleSpinBox_kongtoukai = QtGui.QDoubleSpinBox(self.groupBox_trade_args)
        self.doubleSpinBox_kongtoukai.setGeometry(QtCore.QRect(78, 180, 120, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_kongtoukai.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_kongtoukai.setSizePolicy(sizePolicy)
        self.doubleSpinBox_kongtoukai.setBaseSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_kongtoukai.setMinimum(-99999999.0)
        self.doubleSpinBox_kongtoukai.setMaximum(99999999.0)
        self.doubleSpinBox_kongtoukai.setProperty("value", -12345678.0)
        self.doubleSpinBox_kongtoukai.setObjectName(_fromUtf8("doubleSpinBox_kongtoukai"))
        self.doubleSpinBox_kongtoukai_4 = QtGui.QDoubleSpinBox(self.groupBox_trade_args)
        self.doubleSpinBox_kongtoukai_4.setGeometry(QtCore.QRect(78, 210, 120, 21))
        self.doubleSpinBox_kongtoukai_4.setMinimum(-99999999.0)
        self.doubleSpinBox_kongtoukai_4.setMaximum(99999999.0)
        self.doubleSpinBox_kongtoukai_4.setProperty("value", -12345678.0)
        self.doubleSpinBox_kongtoukai_4.setObjectName(_fromUtf8("doubleSpinBox_kongtoukai_4"))
        self.doubleSpinBox_kongtoukai_3 = QtGui.QDoubleSpinBox(self.groupBox_trade_args)
        self.doubleSpinBox_kongtoukai_3.setGeometry(QtCore.QRect(78, 240, 120, 21))
        self.doubleSpinBox_kongtoukai_3.setMinimum(-99999999.0)
        self.doubleSpinBox_kongtoukai_3.setMaximum(99999999.0)
        self.doubleSpinBox_kongtoukai_3.setProperty("value", -12345678.0)
        self.doubleSpinBox_kongtoukai_3.setObjectName(_fromUtf8("doubleSpinBox_kongtoukai_3"))
        self.doubleSpinBox_kongtoukai_2 = QtGui.QDoubleSpinBox(self.groupBox_trade_args)
        self.doubleSpinBox_kongtoukai_2.setGeometry(QtCore.QRect(78, 270, 120, 21))
        self.doubleSpinBox_kongtoukai_2.setMinimum(-99999999.0)
        self.doubleSpinBox_kongtoukai_2.setMaximum(99999999.0)
        self.doubleSpinBox_kongtoukai_2.setProperty("value", -12345678.0)
        self.doubleSpinBox_kongtoukai_2.setObjectName(_fromUtf8("doubleSpinBox_kongtoukai_2"))
        self.label_Ajinsell_2 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Ajinsell_2.setGeometry(QtCore.QRect(212, 120, 38, 16))
        self.label_Ajinsell_2.setObjectName(_fromUtf8("label_Ajinsell_2"))
        self.spinBox_meifen_3 = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_meifen_3.setGeometry(QtCore.QRect(256, 120, 40, 21))
        self.spinBox_meifen_3.setObjectName(_fromUtf8("spinBox_meifen_3"))
        self.label_Ajinsell_3 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Ajinsell_3.setGeometry(QtCore.QRect(212, 150, 38, 16))
        self.label_Ajinsell_3.setObjectName(_fromUtf8("label_Ajinsell_3"))
        self.spinBox_meifen_4 = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_meifen_4.setGeometry(QtCore.QRect(256, 150, 40, 21))
        self.spinBox_meifen_4.setObjectName(_fromUtf8("spinBox_meifen_4"))
        self.label_Asellchicang = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Asellchicang.setGeometry(QtCore.QRect(212, 180, 38, 16))
        self.label_Asellchicang.setObjectName(_fromUtf8("label_Asellchicang"))
        self.lineEdit_Asellchicang = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Asellchicang.setGeometry(QtCore.QRect(256, 180, 40, 21))
        self.lineEdit_Asellchicang.setObjectName(_fromUtf8("lineEdit_Asellchicang"))
        self.label_Bbuychicang = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Bbuychicang.setGeometry(QtCore.QRect(212, 210, 38, 16))
        self.label_Bbuychicang.setObjectName(_fromUtf8("label_Bbuychicang"))
        self.lineEdit_Asellchicang_4 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Asellchicang_4.setGeometry(QtCore.QRect(256, 210, 40, 21))
        self.lineEdit_Asellchicang_4.setObjectName(_fromUtf8("lineEdit_Asellchicang_4"))
        self.label_Abuychicang = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Abuychicang.setGeometry(QtCore.QRect(212, 240, 38, 16))
        self.label_Abuychicang.setObjectName(_fromUtf8("label_Abuychicang"))
        self.lineEdit_Asellchicang_3 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Asellchicang_3.setGeometry(QtCore.QRect(256, 240, 40, 21))
        self.lineEdit_Asellchicang_3.setObjectName(_fromUtf8("lineEdit_Asellchicang_3"))
        self.label_Bsellchicang = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Bsellchicang.setGeometry(QtCore.QRect(212, 270, 38, 16))
        self.label_Bsellchicang.setObjectName(_fromUtf8("label_Bsellchicang"))
        self.lineEdit_Asellchicang_2 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Asellchicang_2.setGeometry(QtCore.QRect(256, 270, 40, 21))
        self.lineEdit_Asellchicang_2.setObjectName(_fromUtf8("lineEdit_Asellchicang_2"))
        self.label_Ajinsell_4 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Ajinsell_4.setGeometry(QtCore.QRect(280, 90, 60, 16))
        self.label_Ajinsell_4.setObjectName(_fromUtf8("label_Ajinsell_4"))
        self.lineEdit_Ajinsell_4 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Ajinsell_4.setGeometry(QtCore.QRect(348, 90, 40, 21))
        self.lineEdit_Ajinsell_4.setObjectName(_fromUtf8("lineEdit_Ajinsell_4"))
        self.label_Ajinsell_5 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Ajinsell_5.setGeometry(QtCore.QRect(303, 120, 53, 16))
        self.label_Ajinsell_5.setObjectName(_fromUtf8("label_Ajinsell_5"))
        self.lineEdit_Ajinsell_7 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Ajinsell_7.setGeometry(QtCore.QRect(348, 120, 40, 21))
        self.lineEdit_Ajinsell_7.setObjectName(_fromUtf8("lineEdit_Ajinsell_7"))
        self.label_Ajinsell_6 = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Ajinsell_6.setGeometry(QtCore.QRect(303, 150, 53, 16))
        self.label_Ajinsell_6.setObjectName(_fromUtf8("label_Ajinsell_6"))
        self.lineEdit_Ajinsell_8 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Ajinsell_8.setGeometry(QtCore.QRect(348, 150, 40, 21))
        self.lineEdit_Ajinsell_8.setObjectName(_fromUtf8("lineEdit_Ajinsell_8"))
        self.label_Ajinsell = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Ajinsell.setGeometry(QtCore.QRect(306, 180, 38, 16))
        self.label_Ajinsell.setObjectName(_fromUtf8("label_Ajinsell"))
        self.lineEdit_Asellchicang_5 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Asellchicang_5.setGeometry(QtCore.QRect(348, 180, 40, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Asellchicang_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_Asellchicang_5.setSizePolicy(sizePolicy)
        self.lineEdit_Asellchicang_5.setObjectName(_fromUtf8("lineEdit_Asellchicang_5"))
        self.label_Bjinbuy = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Bjinbuy.setGeometry(QtCore.QRect(306, 210, 38, 16))
        self.label_Bjinbuy.setObjectName(_fromUtf8("label_Bjinbuy"))
        self.lineEdit_Asellchicang_7 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Asellchicang_7.setGeometry(QtCore.QRect(348, 210, 40, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Asellchicang_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_Asellchicang_7.setSizePolicy(sizePolicy)
        self.lineEdit_Asellchicang_7.setObjectName(_fromUtf8("lineEdit_Asellchicang_7"))
        self.label_Ajinbuy = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Ajinbuy.setGeometry(QtCore.QRect(306, 240, 38, 16))
        self.label_Ajinbuy.setObjectName(_fromUtf8("label_Ajinbuy"))
        self.lineEdit_Asellchicang_6 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Asellchicang_6.setGeometry(QtCore.QRect(348, 240, 40, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Asellchicang_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_Asellchicang_6.setSizePolicy(sizePolicy)
        self.lineEdit_Asellchicang_6.setObjectName(_fromUtf8("lineEdit_Asellchicang_6"))
        self.label_Bjinsell = QtGui.QLabel(self.groupBox_trade_args)
        self.label_Bjinsell.setGeometry(QtCore.QRect(306, 270, 38, 16))
        self.label_Bjinsell.setObjectName(_fromUtf8("label_Bjinsell"))
        self.lineEdit_Asellchicang_8 = QtGui.QLineEdit(self.groupBox_trade_args)
        self.lineEdit_Asellchicang_8.setGeometry(QtCore.QRect(348, 270, 40, 21))
        self.lineEdit_Asellchicang_8.setObjectName(_fromUtf8("lineEdit_Asellchicang_8"))
        self.pushButton = QtGui.QPushButton(self.groupBox_trade_args)
        self.pushButton.setGeometry(QtCore.QRect(112, 300, 50, 22))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_trade_args)
        self.pushButton_2.setGeometry(QtCore.QRect(112, 326, 50, 22))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_zhisuntiaoshu = QtGui.QLabel(self.groupBox_trade_args)
        self.label_zhisuntiaoshu.setGeometry(QtCore.QRect(6, 90, 33, 16))
        self.label_zhisuntiaoshu.setObjectName(_fromUtf8("label_zhisuntiaoshu"))
        self.spinBox_zhisuntiaoshu = QtGui.QSpinBox(self.groupBox_trade_args)
        self.spinBox_zhisuntiaoshu.setGeometry(QtCore.QRect(46, 90, 42, 21))
        self.spinBox_zhisuntiaoshu.setObjectName(_fromUtf8("spinBox_zhisuntiaoshu"))
        self.pushButton_set_strategy = QtGui.QPushButton(self.groupBox_trade_args)
        self.pushButton_set_strategy.setEnabled(True)
        self.pushButton_set_strategy.setGeometry(QtCore.QRect(176, 300, 100, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_set_strategy.sizePolicy().hasHeightForWidth())
        self.pushButton_set_strategy.setSizePolicy(sizePolicy)
        self.pushButton_set_strategy.setObjectName(_fromUtf8("pushButton_set_strategy"))
        self.pushButton_query_strategy = QtGui.QPushButton(self.groupBox_trade_args)
        self.pushButton_query_strategy.setGeometry(QtCore.QRect(290, 300, 100, 50))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_query_strategy.sizePolicy().hasHeightForWidth())
        self.pushButton_query_strategy.setSizePolicy(sizePolicy)
        self.pushButton_query_strategy.setObjectName(_fromUtf8("pushButton_query_strategy"))
        self.horizontalLayout.addWidget(self.groupBox_trade_args)
        self.horizontalLayout.setStretch(0, 13)
        self.horizontalLayout.setStretch(1, 6)
        self.verticalLayout.addWidget(self.container_trade)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.tab_accounts.addTab(self.tab_account1, _fromUtf8(""))
        self.tab_account2 = QtGui.QWidget()
        self.tab_account2.setObjectName(_fromUtf8("tab_account2"))
        self.tab_accounts.addTab(self.tab_account2, _fromUtf8(""))
        self.tab_account3 = QtGui.QWidget()
        self.tab_account3.setObjectName(_fromUtf8("tab_account3"))
        self.tab_accounts.addTab(self.tab_account3, _fromUtf8(""))
        self.tab_account4 = QtGui.QWidget()
        self.tab_account4.setObjectName(_fromUtf8("tab_account4"))
        self.tab_accounts.addTab(self.tab_account4, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tab_accounts)
        self.tab_records = QtGui.QTabWidget(self.centralWidget)
        self.tab_records.setObjectName(_fromUtf8("tab_records"))
        self.tab_order = QtGui.QWidget()
        self.tab_order.setObjectName(_fromUtf8("tab_order"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_order)
        self.horizontalLayout_4.setMargin(5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.container_order = QtGui.QWidget(self.tab_order)
        self.container_order.setObjectName(_fromUtf8("container_order"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.container_order)
        self.horizontalLayout_3.setMargin(5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableWidget_all_orders = QtGui.QTableWidget(self.container_order)
        self.tableWidget_all_orders.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_all_orders.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_all_orders.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_all_orders.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.tableWidget_all_orders.setObjectName(_fromUtf8("tableWidget_all_orders"))
        self.tableWidget_all_orders.setColumnCount(16)
        self.tableWidget_all_orders.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_all_orders.setItem(0, 14, item)
        self.tableWidget_all_orders.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.tableWidget_all_orders)
        self.groupBox_order_insert = QtGui.QGroupBox(self.container_order)
        self.groupBox_order_insert.setAutoFillBackground(False)
        self.groupBox_order_insert.setObjectName(_fromUtf8("groupBox_order_insert"))
        self.label_buyorsell = QtGui.QLabel(self.groupBox_order_insert)
        self.label_buyorsell.setGeometry(QtCore.QRect(8, 69, 30, 16))
        self.label_buyorsell.setObjectName(_fromUtf8("label_buyorsell"))
        self.lineEdit_heyue = QtGui.QLineEdit(self.groupBox_order_insert)
        self.lineEdit_heyue.setGeometry(QtCore.QRect(70, 21, 117, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_heyue.sizePolicy().hasHeightForWidth())
        self.lineEdit_heyue.setSizePolicy(sizePolicy)
        self.lineEdit_heyue.setObjectName(_fromUtf8("lineEdit_heyue"))
        self.label_heyue = QtGui.QLabel(self.groupBox_order_insert)
        self.label_heyue.setGeometry(QtCore.QRect(8, 32, 30, 16))
        self.label_heyue.setObjectName(_fromUtf8("label_heyue"))
        self.radioButton_kaicang = QtGui.QRadioButton(self.groupBox_order_insert)
        self.radioButton_kaicang.setGeometry(QtCore.QRect(70, 93, 57, 19))
        self.radioButton_kaicang.setObjectName(_fromUtf8("radioButton_kaicang"))
        self.radioButton_maichu = QtGui.QRadioButton(self.groupBox_order_insert)
        self.radioButton_maichu.setGeometry(QtCore.QRect(130, 69, 57, 19))
        self.radioButton_maichu.setObjectName(_fromUtf8("radioButton_maichu"))
        self.label_kaiping = QtGui.QLabel(self.groupBox_order_insert)
        self.label_kaiping.setGeometry(QtCore.QRect(8, 93, 30, 16))
        self.label_kaiping.setObjectName(_fromUtf8("label_kaiping"))
        self.label_shoushu = QtGui.QLabel(self.groupBox_order_insert)
        self.label_shoushu.setGeometry(QtCore.QRect(8, 117, 30, 16))
        self.label_shoushu.setObjectName(_fromUtf8("label_shoushu"))
        self.radioButton_pingcang = QtGui.QRadioButton(self.groupBox_order_insert)
        self.radioButton_pingcang.setGeometry(QtCore.QRect(130, 93, 57, 19))
        self.radioButton_pingcang.setObjectName(_fromUtf8("radioButton_pingcang"))
        self.spinBox_shoushu = QtGui.QSpinBox(self.groupBox_order_insert)
        self.spinBox_shoushu.setGeometry(QtCore.QRect(70, 117, 42, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_shoushu.sizePolicy().hasHeightForWidth())
        self.spinBox_shoushu.setSizePolicy(sizePolicy)
        self.spinBox_shoushu.setObjectName(_fromUtf8("spinBox_shoushu"))
        self.radioButton_pingjin = QtGui.QRadioButton(self.groupBox_order_insert)
        self.radioButton_pingjin.setGeometry(QtCore.QRect(192, 93, 57, 19))
        self.radioButton_pingjin.setObjectName(_fromUtf8("radioButton_pingjin"))
        self.radioButton_mairu = QtGui.QRadioButton(self.groupBox_order_insert)
        self.radioButton_mairu.setGeometry(QtCore.QRect(70, 69, 57, 19))
        self.radioButton_mairu.setObjectName(_fromUtf8("radioButton_mairu"))
        self.doubleSpinBox_xiadanjiage = QtGui.QDoubleSpinBox(self.groupBox_order_insert)
        self.doubleSpinBox_xiadanjiage.setGeometry(QtCore.QRect(70, 157, 90, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_xiadanjiage.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_xiadanjiage.setSizePolicy(sizePolicy)
        self.doubleSpinBox_xiadanjiage.setMaximum(99999.0)
        self.doubleSpinBox_xiadanjiage.setProperty("value", 12345.67)
        self.doubleSpinBox_xiadanjiage.setObjectName(_fromUtf8("doubleSpinBox_xiadanjiage"))
        self.label_xiadanjiage = QtGui.QLabel(self.groupBox_order_insert)
        self.label_xiadanjiage.setGeometry(QtCore.QRect(8, 157, 30, 16))
        self.label_xiadanjiage.setObjectName(_fromUtf8("label_xiadanjiage"))
        self.pushButton_xiadantiaocang = QtGui.QPushButton(self.groupBox_order_insert)
        self.pushButton_xiadantiaocang.setGeometry(QtCore.QRect(192, 251, 93, 28))
        self.pushButton_xiadantiaocang.setObjectName(_fromUtf8("pushButton_xiadantiaocang"))
        self.pushButton_xiandan = QtGui.QPushButton(self.groupBox_order_insert)
        self.pushButton_xiandan.setGeometry(QtCore.QRect(8, 218, 181, 61))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_xiandan.sizePolicy().hasHeightForWidth())
        self.pushButton_xiandan.setSizePolicy(sizePolicy)
        self.pushButton_xiandan.setObjectName(_fromUtf8("pushButton_xiandan"))
        self.pushButton_xiadanquxiao = QtGui.QPushButton(self.groupBox_order_insert)
        self.pushButton_xiadanquxiao.setGeometry(QtCore.QRect(192, 218, 93, 28))
        self.pushButton_xiadanquxiao.setObjectName(_fromUtf8("pushButton_xiadanquxiao"))
        self.label_pankouguadansell = QtGui.QLabel(self.groupBox_order_insert)
        self.label_pankouguadansell.setGeometry(QtCore.QRect(192, 157, 95, 16))
        self.label_pankouguadansell.setObjectName(_fromUtf8("label_pankouguadansell"))
        self.label_dietingjia = QtGui.QLabel(self.groupBox_order_insert)
        self.label_dietingjia.setGeometry(QtCore.QRect(192, 178, 55, 16))
        self.label_dietingjia.setObjectName(_fromUtf8("label_dietingjia"))
        self.label_zuidashoushu = QtGui.QLabel(self.groupBox_order_insert)
        self.label_zuidashoushu.setGeometry(QtCore.QRect(192, 117, 23, 16))
        self.label_zuidashoushu.setObjectName(_fromUtf8("label_zuidashoushu"))
        self.label_zhangtingjia = QtGui.QLabel(self.groupBox_order_insert)
        self.label_zhangtingjia.setGeometry(QtCore.QRect(192, 137, 55, 16))
        self.label_zhangtingjia.setObjectName(_fromUtf8("label_zhangtingjia"))
        self.label_pankouguadanbuy = QtGui.QLabel(self.groupBox_order_insert)
        self.label_pankouguadanbuy.setGeometry(QtCore.QRect(192, 198, 103, 16))
        self.label_pankouguadanbuy.setObjectName(_fromUtf8("label_pankouguadanbuy"))
        self.checkBox_taoli = QtGui.QCheckBox(self.groupBox_order_insert)
        self.checkBox_taoli.setGeometry(QtCore.QRect(192, 21, 57, 19))
        self.checkBox_taoli.setObjectName(_fromUtf8("checkBox_taoli"))
        self.checkBox_baozhi = QtGui.QCheckBox(self.groupBox_order_insert)
        self.checkBox_baozhi.setGeometry(QtCore.QRect(192, 45, 57, 19))
        self.checkBox_baozhi.setObjectName(_fromUtf8("checkBox_baozhi"))
        self.horizontalLayout_3.addWidget(self.groupBox_order_insert)
        self.horizontalLayout_3.setStretch(0, 13)
        self.horizontalLayout_3.setStretch(1, 6)
        self.horizontalLayout_4.addWidget(self.container_order)
        self.tab_records.addTab(self.tab_order, _fromUtf8(""))
        self.tab_unmatched = QtGui.QWidget()
        self.tab_unmatched.setObjectName(_fromUtf8("tab_unmatched"))
        self.tab_records.addTab(self.tab_unmatched, _fromUtf8(""))
        self.tab_transaction = QtGui.QWidget()
        self.tab_transaction.setObjectName(_fromUtf8("tab_transaction"))
        self.tab_records.addTab(self.tab_transaction, _fromUtf8(""))
        self.tab_position = QtGui.QWidget()
        self.tab_position.setObjectName(_fromUtf8("tab_position"))
        self.tab_records.addTab(self.tab_position, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tab_records)
        self.verticalLayout_2.setStretch(0, 6)
        self.verticalLayout_2.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1276, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu_file = QtGui.QMenu(self.menuBar)
        self.menu_file.setObjectName(_fromUtf8("menu_file"))
        self.menu_account = QtGui.QMenu(self.menuBar)
        self.menu_account.setObjectName(_fromUtf8("menu_account"))
        self.menu_market = QtGui.QMenu(self.menuBar)
        self.menu_market.setObjectName(_fromUtf8("menu_market"))
        self.menu_trademodel = QtGui.QMenu(self.menuBar)
        self.menu_trademodel.setObjectName(_fromUtf8("menu_trademodel"))
        self.menu_report = QtGui.QMenu(self.menuBar)
        self.menu_report.setObjectName(_fromUtf8("menu_report"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar.addAction(self.menu_file.menuAction())
        self.menuBar.addAction(self.menu_account.menuAction())
        self.menuBar.addAction(self.menu_market.menuAction())
        self.menuBar.addAction(self.menu_trademodel.menuAction())
        self.menuBar.addAction(self.menu_report.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_accounts.setCurrentIndex(0)
        self.tab_records.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QCTP", None))
        self.label_dongtaiquanyi.setText(_translate("MainWindow", "动态权益", None))
        self.label_value_dongtaiquanyi.setText(_translate("MainWindow", "10000000", None))
        self.label_jingtaiquanyi.setText(_translate("MainWindow", "静态权益", None))
        self.label_value_jingtaiquanyi.setText(_translate("MainWindow", "10000000", None))
        self.label_chicangyingkui.setText(_translate("MainWindow", "持仓盈亏", None))
        self.label_value_chicangyingkui.setText(_translate("MainWindow", "10000000", None))
        self.label_pingcangyingkui.setText(_translate("MainWindow", "平仓盈亏", None))
        self.label_value_pingcangyingkui.setText(_translate("MainWindow", "10000000", None))
        self.label_shouxufei.setText(_translate("MainWindow", "手续费", None))
        self.label_value_shouxufei.setText(_translate("MainWindow", "10000000", None))
        self.label_keyongzijin.setText(_translate("MainWindow", "可用资金", None))
        self.label_value_keyongzijin.setText(_translate("MainWindow", "10000000", None))
        self.label_zhanyongbaozhengjin.setText(_translate("MainWindow", "占用保证金", None))
        self.label_value_zhanyongbaozhengjin.setText(_translate("MainWindow", "10000000", None))
        self.label_xiadandongjie.setText(_translate("MainWindow", "下单冻结", None))
        self.label_value_xiadandongjie.setText(_translate("MainWindow", "10000000", None))
        self.label_fengxiandu.setText(_translate("MainWindow", "风险度", None))
        self.label_value_fengxiandu.setText(_translate("MainWindow", "0", None))
        self.label_jinrirujin.setText(_translate("MainWindow", "今日入金", None))
        self.label_value_jinrirujin.setText(_translate("MainWindow", "10000000", None))
        self.label_jinrichujin.setText(_translate("MainWindow", "今日出金", None))
        self.label_value_jinrichujin.setText(_translate("MainWindow", "10000000", None))
        self.pushButton_query_account.setText(_translate("MainWindow", "查询账户", None))
        self.pushButton_only_close.setText(_translate("MainWindow", "只能平仓", None))
        self.pushButton_start_strategy.setText(_translate("MainWindow", "开始策略", None))
        item = self.tablewidget_tableWidget_Trade_Args.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tablewidget_tableWidget_Trade_Args.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "策略开关", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "期货账号", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "策略编号", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "交易合约", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "新建列", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "交易模型参数", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "持仓盈亏", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "手续费", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "总持仓", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "买持仓", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "新建列", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "卖持仓", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "成交量", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "成交金额", None))
        item = self.tablewidget_tableWidget_Trade_Args.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "平均滑点", None))
        __sortingEnabled = self.tablewidget_tableWidget_Trade_Args.isSortingEnabled()
        self.tablewidget_tableWidget_Trade_Args.setSortingEnabled(False)
        item = self.tablewidget_tableWidget_Trade_Args.item(0, 0)
        item.setText(_translate("MainWindow", "开", None))
        item = self.tablewidget_tableWidget_Trade_Args.item(0, 1)
        item.setText(_translate("MainWindow", "800xxxx", None))
        item = self.tablewidget_tableWidget_Trade_Args.item(1, 0)
        item.setText(_translate("MainWindow", "关", None))
        self.tablewidget_tableWidget_Trade_Args.setSortingEnabled(__sortingEnabled)
        self.groupBox_trade_args.setTitle(_translate("MainWindow", "策略参数", None))
        self.label_kongtoujiacha.setText(_translate("MainWindow", "空头价差", None))
        self.label_qihuozhanghao.setText(_translate("MainWindow", "期货账号", None))
        self.label_jiaoyimoxing.setText(_translate("MainWindow", "交易模型", None))
        self.label_jiacharangjia.setText(_translate("MainWindow", "让价", None))
        self.label_duotoujiacha.setText(_translate("MainWindow", "多头价差", None))
        self.checkBox_jiachaliandong_2.setText(_translate("MainWindow", "空头开", None))
        self.checkBox_jiachaliandong_4.setText(_translate("MainWindow", "多头平", None))
        self.checkBox_jiachaliandong_3.setText(_translate("MainWindow", "多头开", None))
        self.label_zongshou.setText(_translate("MainWindow", "总手", None))
        self.comboBox_qihuozhanghao.setItemText(0, _translate("MainWindow", "8600123456", None))
        self.checkBox_jiachaliandong_5.setText(_translate("MainWindow", "空头平", None))
        self.label_celuebianhao.setText(_translate("MainWindow", "策略编号", None))
        self.comboBox_celuebianhao.setItemText(0, _translate("MainWindow", "99", None))
        self.label_xiadansuanfa.setText(_translate("MainWindow", "下单算法", None))
        self.label_meifen.setText(_translate("MainWindow", "每份", None))
        self.lineEdit_kongtoujiacha.setText(_translate("MainWindow", "-12345678.00", None))
        self.lineEdit_duotoujiacha.setText(_translate("MainWindow", "-12345678.00", None))
        self.label_Ajinsell_2.setText(_translate("MainWindow", "A等待", None))
        self.label_Ajinsell_3.setText(_translate("MainWindow", "B等待", None))
        self.label_Asellchicang.setText(_translate("MainWindow", "A总卖", None))
        self.lineEdit_Asellchicang.setText(_translate("MainWindow", "9999", None))
        self.label_Bbuychicang.setText(_translate("MainWindow", "B总买", None))
        self.lineEdit_Asellchicang_4.setText(_translate("MainWindow", "9999", None))
        self.label_Abuychicang.setText(_translate("MainWindow", "A总买", None))
        self.lineEdit_Asellchicang_3.setText(_translate("MainWindow", "9999", None))
        self.label_Bsellchicang.setText(_translate("MainWindow", "B总卖", None))
        self.lineEdit_Asellchicang_2.setText(_translate("MainWindow", "9999", None))
        self.label_Ajinsell_4.setText(_translate("MainWindow", "撤单限制", None))
        self.lineEdit_Ajinsell_4.setText(_translate("MainWindow", "450", None))
        self.label_Ajinsell_5.setText(_translate("MainWindow", "A撤单", None))
        self.lineEdit_Ajinsell_7.setText(_translate("MainWindow", "450", None))
        self.label_Ajinsell_6.setText(_translate("MainWindow", "B撤单", None))
        self.lineEdit_Ajinsell_8.setText(_translate("MainWindow", "450", None))
        self.label_Ajinsell.setText(_translate("MainWindow", "A今卖", None))
        self.lineEdit_Asellchicang_5.setText(_translate("MainWindow", "9999", None))
        self.label_Bjinbuy.setText(_translate("MainWindow", "B今买", None))
        self.lineEdit_Asellchicang_7.setText(_translate("MainWindow", "9999", None))
        self.label_Ajinbuy.setText(_translate("MainWindow", "A今买", None))
        self.lineEdit_Asellchicang_6.setText(_translate("MainWindow", "9999", None))
        self.label_Bjinsell.setText(_translate("MainWindow", "B今卖", None))
        self.lineEdit_Asellchicang_8.setText(_translate("MainWindow", "9999", None))
        self.pushButton.setText(_translate("MainWindow", "▲", None))
        self.pushButton_2.setText(_translate("MainWindow", "▼", None))
        self.label_zhisuntiaoshu.setText(_translate("MainWindow", "止损", None))
        self.pushButton_set_strategy.setText(_translate("MainWindow", "确定", None))
        self.pushButton_query_strategy.setText(_translate("MainWindow", "查询", None))
        self.tab_accounts.setTabText(self.tab_accounts.indexOf(self.tab_account1), _translate("MainWindow", "所有账户", None))
        self.tab_accounts.setTabText(self.tab_accounts.indexOf(self.tab_account2), _translate("MainWindow", "800658", None))
        self.tab_accounts.setTabText(self.tab_accounts.indexOf(self.tab_account3), _translate("MainWindow", "800669", None))
        self.tab_accounts.setTabText(self.tab_accounts.indexOf(self.tab_account4), _translate("MainWindow", "86001780", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "期货账号", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "策略编号", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "合约", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "买卖", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "开平", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "挂单状态", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "报单价格", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "报单手数", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "未成交手数", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "成交手数", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "详细状态", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "报单时间", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "最后成交时间", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "报单编号", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "投保", None))
        item = self.tableWidget_all_orders.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "交易所", None))
        __sortingEnabled = self.tableWidget_all_orders.isSortingEnabled()
        self.tableWidget_all_orders.setSortingEnabled(False)
        item = self.tableWidget_all_orders.item(0, 0)
        item.setText(_translate("MainWindow", "800658", None))
        item = self.tableWidget_all_orders.item(0, 1)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_all_orders.item(0, 2)
        item.setText(_translate("MainWindow", "cu1610", None))
        item = self.tableWidget_all_orders.item(0, 3)
        item.setText(_translate("MainWindow", "买", None))
        item = self.tableWidget_all_orders.item(0, 4)
        item.setText(_translate("MainWindow", "开", None))
        item = self.tableWidget_all_orders.item(0, 5)
        item.setText(_translate("MainWindow", "未成交", None))
        item = self.tableWidget_all_orders.item(0, 6)
        item.setText(_translate("MainWindow", "82990", None))
        item = self.tableWidget_all_orders.item(0, 7)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_all_orders.item(0, 8)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidget_all_orders.item(0, 9)
        item.setText(_translate("MainWindow", "0", None))
        item = self.tableWidget_all_orders.item(0, 10)
        item.setText(_translate("MainWindow", "未成交", None))
        item = self.tableWidget_all_orders.item(0, 13)
        item.setText(_translate("MainWindow", "291759", None))
        item = self.tableWidget_all_orders.item(0, 14)
        item.setText(_translate("MainWindow", "投机", None))
        self.tableWidget_all_orders.setSortingEnabled(__sortingEnabled)
        self.groupBox_order_insert.setTitle(_translate("MainWindow", "下单板", None))
        self.label_buyorsell.setText(_translate("MainWindow", "买卖", None))
        self.lineEdit_heyue.setText(_translate("MainWindow", "cu1601", None))
        self.label_heyue.setText(_translate("MainWindow", "合约", None))
        self.radioButton_kaicang.setText(_translate("MainWindow", "开仓", None))
        self.radioButton_maichu.setText(_translate("MainWindow", "卖出", None))
        self.label_kaiping.setText(_translate("MainWindow", "开平", None))
        self.label_shoushu.setText(_translate("MainWindow", "手数", None))
        self.radioButton_pingcang.setText(_translate("MainWindow", "平仓", None))
        self.radioButton_pingjin.setText(_translate("MainWindow", "平今", None))
        self.radioButton_mairu.setText(_translate("MainWindow", "买入", None))
        self.label_xiadanjiage.setText(_translate("MainWindow", "价格", None))
        self.pushButton_xiadantiaocang.setText(_translate("MainWindow", "调仓", None))
        self.pushButton_xiandan.setText(_translate("MainWindow", "下单", None))
        self.pushButton_xiadanquxiao.setText(_translate("MainWindow", "取消", None))
        self.label_pankouguadansell.setText(_translate("MainWindow", "卖 82990 / 3", None))
        self.label_dietingjia.setText(_translate("MainWindow", "↓88020", None))
        self.label_zuidashoushu.setText(_translate("MainWindow", "≤0", None))
        self.label_zhangtingjia.setText(_translate("MainWindow", "↑88020", None))
        self.label_pankouguadanbuy.setText(_translate("MainWindow", "买 82970 / 20", None))
        self.checkBox_taoli.setText(_translate("MainWindow", "套利", None))
        self.checkBox_baozhi.setText(_translate("MainWindow", "保值", None))
        self.tab_records.setTabText(self.tab_records.indexOf(self.tab_order), _translate("MainWindow", "所有委托单", None))
        self.tab_records.setTabText(self.tab_records.indexOf(self.tab_unmatched), _translate("MainWindow", "未成交单", None))
        self.tab_records.setTabText(self.tab_records.indexOf(self.tab_transaction), _translate("MainWindow", "成交记录", None))
        self.tab_records.setTabText(self.tab_records.indexOf(self.tab_position), _translate("MainWindow", "持仓", None))
        self.menu_file.setTitle(_translate("MainWindow", "文件", None))
        self.menu_account.setTitle(_translate("MainWindow", "账户", None))
        self.menu_market.setTitle(_translate("MainWindow", "行情", None))
        self.menu_trademodel.setTitle(_translate("MainWindow", "交易模型", None))
        self.menu_report.setTitle(_translate("MainWindow", "报告", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

